// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aacvjcruqevqgfzcffsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhY3ZqY3J1cWV2cWdmemNmZnNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NDE3NjYsImV4cCI6MjA2MTIxNzc2Nn0.1fg9q-hxN_80gM6e54WLdo3gXF7oGfU32IR9XpktH_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);